# Generated by Django 2.1.7 on 2019-07-30 14:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20190730_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperInfo',
            fields=[
                ('paper_id', models.CharField(default=uuid.UUID('3f9607d9-3951-4569-b044-e44dc83249d0'), editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='试卷ID')),
                ('title', models.CharField(max_length=50, verbose_name='试卷标题')),
                ('degree', models.IntegerField(default=0, verbose_name='难度')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否分享')),
                ('score', models.FloatField(verbose_name='试卷分数')),
                ('creator_id', models.CharField(max_length=50, verbose_name='创建人')),
                ('owner_id', models.CharField(max_length=50, verbose_name='拥有人')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.SubjectInfo', verbose_name='课程')),
            ],
            options={
                'verbose_name': '试卷信息',
                'verbose_name_plural': '试卷信息',
            },
        ),
    ]
