# Generated by Django 2.1.7 on 2019-08-04 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperinfo',
            name='paper_id',
            field=models.CharField(default=uuid.UUID('3cc56ff6-4f86-430d-97ad-271c8b4e8401'), editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='试卷ID'),
        ),
    ]
