# Generated by Django 2.1.7 on 2019-08-04 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_auto_20190804_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperinfo',
            name='paper_id',
            field=models.CharField(default=uuid.UUID('317b1995-c2a6-40f0-94ac-efd256e0410f'), editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='试卷ID'),
        ),
    ]
