# Generated by Django 2.1.7 on 2019-08-11 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_auto_20190804_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperinfo',
            name='paper_id',
            field=models.CharField(default=uuid.UUID('b98569bc-5201-424a-ae7a-a6aa43ba8e89'), editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='试卷ID'),
        ),
    ]
