# Generated by Django 2.1.7 on 2019-08-04 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationinfo',
            name='examination_id',
            field=models.CharField(default=uuid.UUID('937e0da2-79cf-4b8e-b89a-ec3f470ea383'), editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='考试ID'),
        ),
    ]
