# Generated by Django 2.1.7 on 2019-08-04 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_auto_20190804_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationinfo',
            name='examination_id',
            field=models.CharField(default=uuid.UUID('4a49b72b-a5f8-44f5-bfd5-b1a2614c4756'), editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='考试ID'),
        ),
    ]
