# Generated by Django 2.1.7 on 2019-08-11 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0003_auto_20190804_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationinfo',
            name='examination_id',
            field=models.CharField(default=uuid.UUID('cc02b7e1-b740-4dc1-a074-9ec8c506260b'), editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='考试ID'),
        ),
    ]
