# Generated by Django 2.1.7 on 2019-07-30 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectinfo',
            name='subject_id',
            field=models.CharField(default=uuid.UUID('629eebf7-b35d-4cf5-beae-a25917c9ced7'), editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='科目ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.CharField(default=uuid.UUID('1fc50d2b-b434-42da-b594-62a263b3173c'), editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
    ]
