# Generated by Django 2.1.7 on 2019-08-04 06:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190730_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectinfo',
            name='subject_id',
            field=models.CharField(default=uuid.UUID('b00540f2-2166-453c-92ff-d0eb0ce33413'), editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='科目ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 4, 6, 38, 28, 580988, tzinfo=utc), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.CharField(default=uuid.UUID('017d4249-ba62-47f1-8eb5-a5207d9be64e'), editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
    ]
