# Generated by Django 2.1.7 on 2019-08-04 06:45

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190804_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectinfo',
            name='subject_id',
            field=models.CharField(default=uuid.UUID('248d919d-215d-4635-aeb4-ac180fce688a'), editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='科目ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.CharField(default=uuid.UUID('f8d3bb2d-8e41-4241-8a4b-702546a7ba80'), editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
    ]
