# Generated by Django 2.1.7 on 2019-08-04 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioninfo',
            name='question_id',
            field=models.CharField(default=uuid.UUID('6a3f30c2-55d9-47b0-9017-9710ccc4f984'), editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='试题ID'),
        ),
    ]
