# Generated by Django 2.1.7 on 2019-08-11 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20190804_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioninfo',
            name='question_id',
            field=models.CharField(default=uuid.UUID('4b578746-11bb-432e-86a7-c3e5ea1f5441'), editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='试题ID'),
        ),
    ]
