# Generated by Django 2.1.7 on 2019-07-30 14:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(default=False, verbose_name='是否正确')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.ExaminationInfo', verbose_name='考试信息')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.QuestionInfo', verbose_name='试题信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='考生信息')),
            ],
            options={
                'verbose_name': '学生答题信息',
                'verbose_name_plural': '学生答题信息',
            },
        ),
        migrations.CreateModel(
            name='PaperQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='题目分数')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper.PaperInfo', verbose_name='试卷信息')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.QuestionInfo', verbose_name='试题信息')),
            ],
            options={
                'verbose_name': '试卷-试题关联信息',
                'verbose_name_plural': '试卷-试题关联信息',
            },
        ),
        migrations.CreateModel(
            name='ReportInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(default=0, verbose_name='学生得分')),
                ('submit_time', models.DateTimeField(auto_now=True, verbose_name='提交时间')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.ExaminationInfo', verbose_name='考试信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='考生信息')),
            ],
            options={
                'verbose_name': '考试-试卷关联信息',
                'verbose_name_plural': '考试-试卷关联信息',
            },
        ),
        migrations.CreateModel(
            name='SystemCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=5, verbose_name='类型')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('value', models.IntegerField(verbose_name='Code信息')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统识别码',
                'verbose_name_plural': '系统识别码',
            },
        ),
    ]
